// import { Tour } from "./tour";
// export const MockTours: Tour[] = [
//   {
//     id: "CHG11",
//     name: "China Encounter",
//     availabledTitles: [
//       "Mr",
//       "Mrs",
//       "Ms",
//       "Miss",
//       "Mstr",
//       "Dr",
//       "Prof",
//       "Sir",
//       "Sen"
//     ],
//     availabledCountryOrAreas: [
//       { id: 0, name: "Andorra", code: "AD" },
//       { id: 1, name: "United Arab Emirates", code: "AE" },
//       { id: 2, name: "Afghanistan", code: "AF" },
//       { id: 3, name: "Antigua and Barbuda", code: "AG" },
//       { id: 4, name: "Anguilla", code: "AI" },
//       { id: 5, name: "Albania", code: "AL" },
//       { id: 6, name: "Armenia", code: "AM" },
//       { id: 7, name: "Angola", code: "AO" },
//       { id: 8, name: "Antarctica", code: "AQ" },
//       { id: 9, name: "Argentina", code: "AR" },
//       { id: 10, name: "American Samoa", code: "AS" },
//       { id: 11, name: "Austria", code: "AT" },
//       { id: 12, name: "Australia", code: "AU" },
//       { id: 13, name: "Aruba", code: "AW" },
//       { id: 14, name: "Åland Islands", code: "AX" },
//       { id: 15, name: "Azerbaijan", code: "AZ" },
//       { id: 16, name: "Bosnia and Herzegovina", code: "BA" },
//       { id: 17, name: "Barbados", code: "BB" },
//       { id: 18, name: "Bangladesh", code: "BD" },
//       { id: 19, name: "Belgium", code: "BE" },
//       { id: 20, name: "Burkina Faso", code: "BF" },
//       { id: 21, name: "Bulgaria", code: "BG" },
//       { id: 22, name: "Bahrain", code: "BH" },
//       { id: 23, name: "Burundi", code: "BI" },
//       { id: 24, name: "Benin", code: "BJ" },
//       { id: 25, name: "Saint Barthélemy", code: "BL" },
//       { id: 26, name: "Bermuda", code: "BM" },
//       { id: 27, name: "Brunei Darussalam", code: "BN" },
//       { id: 28, name: "Bolivia", code: "BO" },
//       { id: 29, name: "Caribbean Netherlands", code: "BQ" },
//       { id: 30, name: "Brazil", code: "BR" },
//       { id: 31, name: "Bahamas", code: "BS" },
//       { id: 32, name: "Bhutan", code: "BT" },
//       { id: 33, name: "Bouvet Island", code: "BV" },
//       { id: 34, name: "Botswana", code: "BW" },
//       { id: 35, name: "Belarus", code: "BY" },
//       { id: 36, name: "Belize", code: "BZ" },
//       { id: 37, name: "Canada", code: "CA" },
//       { id: 38, name: "Cocos (Keeling) Islands", code: "CC" },
//       { id: 39, name: "Congo, Democratic Republic of", code: "CD" },
//       { id: 40, name: "Central African Republic", code: "CF" },
//       { id: 41, name: "Congo", code: "CG" },
//       { id: 42, name: "Switzerland", code: "CH" },
//       { id: 43, name: "Côte d'Ivoire", code: "CI" },
//       { id: 44, name: "Cook Islands", code: "CK" },
//       { id: 45, name: "Chile", code: "CL" },
//       { id: 46, name: "Cameroon", code: "CM" },
//       { id: 47, name: "China", code: "CN" },
//       { id: 48, name: "Colombia", code: "CO" },
//       { id: 49, name: "Costa Rica", code: "CR" },
//       { id: 50, name: "Cuba", code: "CU" },
//       { id: 51, name: "Cape Verde", code: "CV" },
//       { id: 52, name: "Curaçao", code: "CW" },
//       { id: 53, name: "Christmas Island", code: "CX" },
//       { id: 54, name: "Cyprus", code: "CY" },
//       { id: 55, name: "Czech Republic", code: "CZ" },
//       { id: 56, name: "Germany", code: "DE" },
//       { id: 57, name: "Djibouti", code: "DJ" },
//       { id: 58, name: "Denmark", code: "DK" },
//       { id: 59, name: "Dominica", code: "DM" },
//       { id: 60, name: "Dominican Republic", code: "DO" },
//       { id: 61, name: "Algeria", code: "DZ" },
//       { id: 62, name: "Ecuador", code: "EC" },
//       { id: 63, name: "Estonia", code: "EE" },
//       { id: 64, name: "Egypt", code: "EG" },
//       { id: 65, name: "Western Sahara", code: "EH" },
//       { id: 66, name: "Eritrea", code: "ER" },
//       { id: 67, name: "Spain", code: "ES" },
//       { id: 68, name: "Ethiopia", code: "ET" },
//       { id: 69, name: "Finland", code: "FI" },
//       { id: 70, name: "Fiji", code: "FJ" },
//       { id: 71, name: "Falkland Islands", code: "FK" },
//       { id: 72, name: "Micronesia, Federated States of", code: "FM" },
//       { id: 73, name: "Faroe Islands", code: "FO" },
//       { id: 74, name: "France", code: "FR" },
//       { id: 75, name: "Gabon", code: "GA" },
//       { id: 76, name: "United Kingdom", code: "GB" },
//       { id: 77, name: "Grenada", code: "GD" },
//       { id: 78, name: "Georgia", code: "GE" },
//       { id: 79, name: "French Guiana", code: "GF" },
//       { id: 80, name: "Guernsey", code: "GG" },
//       { id: 81, name: "Ghana", code: "GH" },
//       { id: 82, name: "Gibraltar", code: "GI" },
//       { id: 83, name: "Greenland", code: "GL" },
//       { id: 84, name: "Gambia", code: "GM" },
//       { id: 85, name: "Guinea", code: "GN" },
//       { id: 86, name: "Guadeloupe", code: "GP" },
//       { id: 87, name: "Equatorial Guinea", code: "GQ" },
//       { id: 88, name: "Greece", code: "GR" },
//       {
//         id: 89,
//         name: "South Georgia and the South Sandwich Islands",
//         code: "GS"
//       },
//       { id: 90, name: "Guatemala", code: "GT" },
//       { id: 91, name: "Guam", code: "GU" },
//       { id: 92, name: "Guinea-Bissau", code: "GW" },
//       { id: 93, name: "Guyana", code: "GY" },
//       { id: 94, name: "Hong Kong", code: "HK" },
//       { id: 95, name: "Heard and McDonald Islands", code: "HM" },
//       { id: 96, name: "Honduras", code: "HN" },
//       { id: 97, name: "Croatia", code: "HR" },
//       { id: 98, name: "Haiti", code: "HT" },
//       { id: 99, name: "Hungary", code: "HU" },
//       { id: 100, name: "Indonesia", code: "ID" },
//       { id: 101, name: "Ireland", code: "IE" },
//       { id: 102, name: "Israel", code: "IL" },
//       { id: 103, name: "Isle of Man", code: "IM" },
//       { id: 104, name: "India", code: "IN" },
//       { id: 105, name: "British Indian Ocean Territory", code: "IO" },
//       { id: 106, name: "Iraq", code: "IQ" },
//       { id: 107, name: "Iran", code: "IR" },
//       { id: 108, name: "Iceland", code: "IS" },
//       { id: 109, name: "Italy", code: "IT" },
//       { id: 110, name: "Jersey", code: "JE" },
//       { id: 111, name: "Jamaica", code: "JM" },
//       { id: 112, name: "Jordan", code: "JO" },
//       { id: 113, name: "Japan", code: "JP" },
//       { id: 114, name: "Kenya", code: "KE" },
//       { id: 115, name: "Kyrgyzstan", code: "KG" },
//       { id: 116, name: "Cambodia", code: "KH" },
//       { id: 117, name: "Kiribati", code: "KI" },
//       { id: 118, name: "Comoros", code: "KM" },
//       { id: 119, name: "Saint Kitts and Nevis", code: "KN" },
//       { id: 120, name: "North Korea", code: "KP" },
//       { id: 121, name: "South Korea", code: "KR" },
//       { id: 122, name: "Kuwait", code: "KW" },
//       { id: 123, name: "Cayman Islands", code: "KY" },
//       { id: 124, name: "Kazakhstan", code: "KZ" },
//       { id: 125, name: "Lao People's Democratic Republic", code: "LA" },
//       { id: 126, name: "Lebanon", code: "LB" },
//       { id: 127, name: "Saint Lucia", code: "LC" },
//       { id: 128, name: "Liechtenstein", code: "LI" },
//       { id: 129, name: "Sri Lanka", code: "LK" },
//       { id: 130, name: "Liberia", code: "LR" },
//       { id: 131, name: "Lesotho", code: "LS" },
//       { id: 132, name: "Lithuania", code: "LT" },
//       { id: 133, name: "Luxembourg", code: "LU" },
//       { id: 134, name: "Latvia", code: "LV" },
//       { id: 135, name: "Libya", code: "LY" },
//       { id: 136, name: "Morocco", code: "MA" },
//       { id: 137, name: "Monaco", code: "MC" },
//       { id: 138, name: "Moldova", code: "MD" },
//       { id: 139, name: "Montenegro", code: "ME" },
//       { id: 140, name: "Saint-Martin (France)", code: "MF" },
//       { id: 141, name: "Madagascar", code: "MG" },
//       { id: 142, name: "Marshall Islands", code: "MH" },
//       { id: 143, name: "Macedonia", code: "MK" },
//       { id: 144, name: "Mali", code: "ML" },
//       { id: 145, name: "Myanmar", code: "MM" },
//       { id: 146, name: "Mongolia", code: "MN" },
//       { id: 147, name: "Macau", code: "MO" },
//       { id: 148, name: "Northern Mariana Islands", code: "MP" },
//       { id: 149, name: "Martinique", code: "MQ" },
//       { id: 150, name: "Mauritania", code: "MR" },
//       { id: 151, name: "Montserrat", code: "MS" },
//       { id: 152, name: "Malta", code: "MT" },
//       { id: 153, name: "Mauritius", code: "MU" },
//       { id: 154, name: "Maldives", code: "MV" },
//       { id: 155, name: "Malawi", code: "MW" },
//       { id: 156, name: "Mexico", code: "MX" },
//       { id: 157, name: "Malaysia", code: "MY" },
//       { id: 158, name: "Mozambique", code: "MZ" },
//       { id: 159, name: "Namibia", code: "NA" },
//       { id: 160, name: "New Caledonia", code: "NC" },
//       { id: 161, name: "Niger", code: "NE" },
//       { id: 162, name: "Norfolk Island", code: "NF" },
//       { id: 163, name: "Nigeria", code: "NG" },
//       { id: 164, name: "Nicaragua", code: "NI" },
//       { id: 165, name: "The Netherlands", code: "NL" },
//       { id: 166, name: "Norway", code: "NO" },
//       { id: 167, name: "Nepal", code: "NP" },
//       { id: 168, name: "Nauru", code: "NR" },
//       { id: 169, name: "Niue", code: "NU" },
//       { id: 170, name: "New Zealand", code: "NZ" },
//       { id: 171, name: "Oman", code: "OM" },
//       { id: 172, name: "Panama", code: "PA" },
//       { id: 173, name: "Peru", code: "PE" },
//       { id: 174, name: "French Polynesia", code: "PF" },
//       { id: 175, name: "Papua New Guinea", code: "PG" },
//       { id: 176, name: "Philippines", code: "PH" },
//       { id: 177, name: "Pakistan", code: "PK" },
//       { id: 178, name: "Poland", code: "PL" },
//       { id: 179, name: "St. Pierre and Miquelon", code: "PM" },
//       { id: 180, name: "Pitcairn", code: "PN" },
//       { id: 181, name: "Puerto Rico", code: "PR" },
//       { id: 182, name: "Palestinian Territory, Occupied", code: "PS" },
//       { id: 183, name: "Portugal", code: "PT" },
//       { id: 184, name: "Palau", code: "PW" },
//       { id: 185, name: "Paraguay", code: "PY" },
//       { id: 186, name: "Qatar", code: "QA" },
//       { id: 187, name: "Reunion", code: "RE" },
//       { id: 188, name: "Romania", code: "RO" },
//       { id: 189, name: "Serbia", code: "RS" },
//       { id: 190, name: "Russian Federation", code: "RU" },
//       { id: 191, name: "Rwanda", code: "RW" },
//       { id: 192, name: "Saudi Arabia", code: "SA" },
//       { id: 193, name: "Solomon Islands", code: "SB" },
//       { id: 194, name: "Seychelles", code: "SC" },
//       { id: 195, name: "Sudan", code: "SD" },
//       { id: 196, name: "Sweden", code: "SE" },
//       { id: 197, name: "Singapore", code: "SG" },
//       { id: 198, name: "Saint Helena", code: "SH" },
//       { id: 199, name: "Slovenia", code: "SI" },
//       { id: 200, name: "Svalbard and Jan Mayen Islands", code: "SJ" },
//       { id: 201, name: "Slovakia (Slovak Republic)", code: "SK" },
//       { id: 202, name: "Sierra Leone", code: "SL" },
//       { id: 203, name: "San Marino", code: "SM" },
//       { id: 204, name: "Senegal", code: "SN" },
//       { id: 205, name: "Somalia", code: "SO" },
//       { id: 206, name: "Suriname", code: "SR" },
//       { id: 207, name: "South Sudan", code: "SS" },
//       { id: 208, name: "Sao Tome and Principe", code: "ST" },
//       { id: 209, name: "El Salvador", code: "SV" },
//       { id: 210, name: "Saint-Martin (Pays-Bas)", code: "SX" },
//       { id: 211, name: "Syria", code: "SY" },
//       { id: 212, name: "Swaziland", code: "SZ" },
//       { id: 213, name: "Turks and Caicos Islands", code: "TC" },
//       { id: 214, name: "Chad", code: "TD" },
//       { id: 215, name: "French Southern Territories", code: "TF" },
//       { id: 216, name: "Togo", code: "TG" },
//       { id: 217, name: "Thailand", code: "TH" },
//       { id: 218, name: "Tajikistan", code: "TJ" },
//       { id: 219, name: "Tokelau", code: "TK" },
//       { id: 220, name: "Timor-Leste", code: "TL" },
//       { id: 221, name: "Turkmenistan", code: "TM" },
//       { id: 222, name: "Tunisia", code: "TN" },
//       { id: 223, name: "Tonga", code: "TO" },
//       { id: 224, name: "Turkey", code: "TR" },
//       { id: 225, name: "Trinidad and Tobago", code: "TT" },
//       { id: 226, name: "Tuvalu", code: "TV" },
//       { id: 227, name: "Taiwan", code: "TW" },
//       { id: 228, name: "Tanzania", code: "TZ" },
//       { id: 229, name: "Ukraine", code: "UA" },
//       { id: 230, name: "Uganda", code: "UG" },
//       { id: 231, name: "United States Minor Outlying Islands", code: "UM" },
//       { id: 232, name: "United States", code: "US" },
//       { id: 233, name: "Uruguay", code: "UY" },
//       { id: 234, name: "Uzbekistan", code: "UZ" },
//       { id: 235, name: "Vatican", code: "VA" },
//       { id: 236, name: "Saint Vincent and the Grenadines", code: "VC" },
//       { id: 237, name: "Venezuela", code: "VE" },
//       { id: 238, name: "Virgin Islands (British)", code: "VG" },
//       { id: 239, name: "Virgin Islands (U.S.)", code: "VI" },
//       { id: 240, name: "Vietnam", code: "VN" },
//       { id: 241, name: "Vanuatu", code: "VU" },
//       { id: 242, name: "Wallis and Futuna Islands", code: "WF" },
//       { id: 243, name: "Samoa", code: "WS" },
//       { id: 244, name: "Yemen", code: "YE" },
//       { id: 245, name: "Mayotte", code: "YT" },
//       { id: 246, name: "South Africa", code: "ZA" },
//       { id: 247, name: "Zambia", code: "ZM" },
//       { id: 248, name: "Zimbabwe", code: "ZW" }
//     ],
//     trips: [
//       {
//         id: "30004810",
//         name: "China Encounter 2-for-1, with Air Canada, 9 Days / 7 Nights",
//         summary:
//           "Experts in travel to China for the past 40 years! Travel to China on this group journey of her key sites staying in good value accommodation with English speaking guides. From the Great Wall and Forbidden City in Beijing to the city of Suzhou, once called the Venice of the East, where you can explore classical gardens and gain insight into the silk trade, to the picturesque town of Wuxi, this trip covers the highlights. You'll then head onward to Hangzhou to discover this cultural gem and city of lore before traveling to Shanghai for a city tour. Complete with English speaking guides, many meals, and more!",
//         remark: "remark",
//         guideline: "<strong>guidelineguidelineguidelineguideline</strong>",
//         selectedTravellerQuantity: { id: 2, name: "Traveller Quantity: 2" },
//         selectedRoomQuantity: { id: 1, name: "Capacity: 1" },
//         availabledRoomQuantities: [
//           { id: 1, name: "Capacity: 1" },
//           { id: 2, name: "Capacity: 2" },
//           { id: 3, name: "Capacity: 3" },
//           { id: 4, name: "Capacity: 4" },
//           { id: 5, name: "Capacity: 5" },
//           { id: 6, name: "Capacity: 6" },
//           { id: 7, name: "Capacity: 7" },
//           { id: 8, name: "Capacity: 8" },
//           { id: 9, name: "Capacity: 9" }
//         ],
//         availabledTravellerQuantities: [
//           { id: 1, name: "Traveller Quantity: 1" },
//           { id: 2, name: "Traveller Quantity: 2" },
//           { id: 3, name: "Traveller Quantity: 3" },
//           { id: 4, name: "Traveller Quantity: 4" },
//           { id: 5, name: "Traveller Quantity: 5" },
//           { id: 6, name: "Traveller Quantity: 6" },
//           { id: 7, name: "Traveller Quantity: 7" },
//           { id: 8, name: "Traveller Quantity: 8" },
//           { id: 9, name: "Traveller Quantity: 9" },
//           { id: 10, name: "Traveller Quantity: 10" },
//           { id: 11, name: "Traveller Quantity: 11" },
//           { id: 12, name: "Traveller Quantity: 12" },
//           { id: 13, name: "Traveller Quantity: 13" },
//           { id: 14, name: "Traveller Quantity: 14" },
//           { id: 15, name: "Traveller Quantity: 15" },
//           { id: 16, name: "Traveller Quantity: 16" },
//           { id: 17, name: "Traveller Quantity: 17" },
//           { id: 18, name: "Traveller Quantity: 18" },
//           { id: 19, name: "Traveller Quantity: 19" }
//         ],
//         startPlace: "Toronto,Edmonton,Ottawa,Montréal,Vancouver,Calgary",
//         endPlace: "Asia,China,Beijing",
//         startCountryOrArea: { id: 37, name: "Canada", code: "CA" },
//         endCountryOrArea: { id: 47, name: "China", code: "CN" },
//         startDate: "September 27, 2018",
//         endDate: "October 5, 2018",
//         tripCostForDefaultPerTraveller: 1449.5,
//         tripCostForDefaultTravellerQuantity: 2.0,
//         tripSingleSupplement: 295.0,
//         minRoomQuantityForTravellers: 1,
//         visaPrice: 50.0,
//         tourInfoSource: "",
//         billingInfo: {
//           firstName: null,
//           lastName: null,
//           email: null,
//           primaryPhone: null,
//           secondaryPhone: null,
//           mailingAddress: null,
//           city: null,
//           country: null,
//           provinceStates: null,
//           postalCode: null,
//           agreeTermAndCondition: false,
//           haveReadTripNotes: false,
//           canReceiveMoreInfo: false
//         },
//         includedIn: [
//           {
//             id: 0,
//             text: "include info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 1,
//             text: "include info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 2,
//             text: "include info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           }
//         ],
//         notIncludeIn: [
//           {
//             id: 0,
//             text: "not IncludeIn info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 1,
//             text: "not IncludeIn info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 2,
//             text: "not IncludeIn info...",
//             tourId: "CHG11",
//             tripId: "30004810"
//           }
//         ],
//         options: [
//           {
//             id: 0,
//             location: "Beijing",
//             name: "Acrobatic Show",
//             price: 50.0,
//             enabled: true,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 1,
//             location: "Hangzhou",
//             name: "Romance of Song Dynasty Show",
//             price: 60.0,
//             enabled: true,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 2,
//             location: "Shanghai",
//             name: "Huangpu River Cruise",
//             price: 50.0,
//             enabled: true,
//             tourId: "CHG11",
//             tripId: "30004810"
//           }
//         ],
//         rooms: [],
//         availabledRooms: [
//           {
//             id: 0,
//             index: 0,
//             beddingConfig: "Single Room(One Single Bed)",
//             capacity: 1,
//             adultMaxQuantity: 1,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: [],
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 1,
//             index: 0,
//             beddingConfig: "Double Room(One King/Queen Bed)",
//             capacity: 2,
//             adultMaxQuantity: 2,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: [],
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 2,
//             index: 0,
//             beddingConfig: "Twin Room(Two Single Beds)",
//             capacity: 2,
//             adultMaxQuantity: 2,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 3,
//             index: 0,
//             beddingConfig:
//               "Triple Room(One King/Queen Bed plus One Single Bed)",
//             capacity: 3,
//             adultMaxQuantity: 3,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 4,
//             index: 0,
//             beddingConfig: "Triple Room(One Double Bed plus One Single Bed)",
//             capacity: 3,
//             adultMaxQuantity: 3,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 5,
//             index: 0,
//             beddingConfig: "Quadruple Room(Two Double Bed)",
//             capacity: 4,
//             adultMaxQuantity: 4,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 6,
//             index: 0,
//             beddingConfig: "Quadruple Room(Two Queen Bed)",
//             capacity: 4,
//             adultMaxQuantity: 4,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           },
//           {
//             id: 7,
//             index: 0,
//             beddingConfig: "Quadruple Room(4 Single Bed)",
//             capacity: 4,
//             adultMaxQuantity: 4,
//             childMaxQuantity: 0,
//             roomPriceForPerTraveller: 1449.5,
//             singleSupplement: 295.0,
//             childDiscount: 0,
//             childPromoAmount: 50,
//             smokingRoom: 0,
//             extraHotelQuantity: 0,
//             travellers: null,
//             tourId: "CHG11",
//             tripId: "30004810"
//           }
//         ],
//         tourId: "CHG11"
//       }
//     ]
//   }
// ];
