import { Room } from "./room";

export const MockRooms: Room[] = [
  {
    id: 1100,
    index: 0,
    beddingConfig: "$750X1 1100",
    capacity: 1,
    roomPrice: 750,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1101,
    index: 0,
    beddingConfig: "$300X2 1101",
    capacity: 2,
    roomPrice: 300,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1102,
    index: 0,
    beddingConfig: "$500X3 1102",
    capacity: 3,
    roomPrice: 500,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1103,
    index: 0,
    beddingConfig: "$560X3 1103",
    capacity: 3,
    roomPrice: 560,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1104,
    index: 0,
    beddingConfig: "$200X2 1104",
    capacity: 2,
    roomPrice: 200,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1201,
    index: 0,
    beddingConfig: "Two bed (double on request) 1201",
    capacity: 4,
    roomPrice: 600,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 2
  },
  {
    id: 1202,
    index: 0,
    beddingConfig: "One bed (double on request) 1202",
    capacity: 2,
    roomPrice: 260,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 2
  },
  {
    id: 2101,
    index: 0,
    beddingConfig: "One bed (double on request) 2101",
    capacity: 2,
    roomPrice: 260,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 2,
    tripId: 1
  },
  {
    id: 2102,
    index: 0,
    beddingConfig: "Two bed (king on request) 2102",
    capacity: 3,
    roomPrice: 270,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 2,
    tripId: 1
  },
  {
    id: 3101,
    index: 0,
    beddingConfig: "One bed (king on request) 3101",
    capacity: 2,
    roomPrice: 280,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 3,
    tripId: 1
  },
  {
    id: 3102,
    index: 0,
    beddingConfig: "Three single beds 3102",
    capacity: 3,
    roomPrice: 290,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 3,
    tripId: 1
  },
  {
    id: 4101,
    index: 0,
    beddingConfig: "Two Single Beds 4101",
    capacity: 2,
    roomPrice: 310,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 4,
    tripId: 1
  },
  {
    id: 4102,
    index: 0,
    beddingConfig: "One bed (double on request) 4102",
    capacity: 3,
    roomPrice: 320,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 4,
    tripId: 1
  },
  {
    id: 4103,
    index: 0,
    beddingConfig: "Two bed (queen on request) 4103",
    capacity: 4,
    roomPrice: 329,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 4,
    tripId: 1
  }
];
