import { Room } from "./room";

export const MockRooms: Room[] = [
  {
    id: 1100,
    index: 0,
    beddingConfig: "One bed (king on request)",
    capacity: 1,
    roomPrice: 750,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1101,
    index: 0,
    beddingConfig: "One bed (king on request)",
    capacity: 2,
    roomPrice: 300,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1102,
    index: 0,
    beddingConfig: "Two bed (queen on request)",
    capacity: 3,
    roomPrice: 500,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1103,
    index: 0,
    beddingConfig: "Two bed (king on request)",
    capacity: 3,
    roomPrice: 560,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1104,
    index: 0,
    beddingConfig: "One bed (queen on request)",
    capacity: 2,
    roomPrice: 200,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 1,
    tripId: 1
  },
  {
    id: 1201,
    index: 0,
    beddingConfig: "Two bed (double on request)",
    capacity: 4,
    roomPrice: 600,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 2
  },
  {
    id: 1202,
    index: 0,
    beddingConfig: "One bed (double on request)",
    capacity: 2,
    roomPrice: 260,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 1,
    tripId: 2
  },
  {
    id: 2101,
    index: 0,
    beddingConfig: "One bed (double on request)",
    capacity: 2,
    roomPrice: 260,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 2,
    tripId: 1
  },
  {
    id: 2102,
    index: 0,
    beddingConfig: "Two bed (king on request)",
    capacity: 3,
    roomPrice: 270,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 2,
    tripId: 1
  },
  {
    id: 3101,
    index: 0,
    beddingConfig: "One bed (king on request)",
    capacity: 2,
    roomPrice: 280,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 3,
    tripId: 1
  },
  {
    id: 3102,
    index: 0,
    beddingConfig: "Three single beds",
    capacity: 3,
    roomPrice: 290,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 3,
    tripId: 1
  },
  {
    id: 4101,
    index: 0,
    beddingConfig: "Two Single Beds",
    capacity: 2,
    roomPrice: 310,
    singleSupplement: 299,
    isSmokingRoom: 1,
    travellers: null,
    tourId: 4,
    tripId: 1
  },
  {
    id: 4102,
    index: 0,
    beddingConfig: "One bed (double on request) and One Single Bed",
    capacity: 3,
    roomPrice: 320,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 4,
    tripId: 1
  },
  {
    id: 4103,
    index: 0,
    beddingConfig: "Two bed (queen on request)",
    capacity: 4,
    roomPrice: 329,
    singleSupplement: 299,
    isSmokingRoom: 0,
    travellers: null,
    tourId: 4,
    tripId: 1
  }
];
